- src/modules/messageBrokerPublisher/connectors/MessageBrokerConnector.ts
- src/modules/webhooks/ConfigModel.ts
- src/modules/webhooks/ConfigParser.ts
- src/modules/webhooks/WebhooksModule.ts
- src/modules/webhooks/WebhooksModuleConfiguration.ts
At some points it can be that services run under a self signed certificate. The only option at the moment is to turn of certificate validation **globally** using the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable which also disables the tls check when accessing the backbone.
Now it is possible to disable tls checks for the webhooks module.
> Allow skipping the tls check for webhooks

- src/index.ts
> Restrict either the SSE or the Sync module to be active but not both

- test/lib/Launcher.ts
Not reusing sockets gets rid of socket hangups during debugging when a connection times out and is closed by the server while the event loop is frozen.
> Fix socket hangups during debugging of tests

- Dockerfile
- config/prod.json
- should be done before -> defaults here are dangerous
- prod will be shutdown soon
> Remove enmeshed-prod as default backbone

- .github/workflows/publish.yml
- .github/workflows/test.yml
`run-checks` was running on node 18 and showed up some errors: https://github.com/nmshd/connector/actions/runs/11237382743/job/31239698267
> Use node current for checks in pipelines

- .ci/runChecks.sh
- package-lock.json
- package.json
- packages/sdk/package.json
- src/infrastructure/httpServer/HttpServer.ts
- src/infrastructure/httpServer/middlewares/genericErrorHandler.ts
- src/modules/coreHttpApi/common/BaseController.ts
- src/modules/coreHttpApi/controllers/AccountController.ts
- src/modules/coreHttpApi/controllers/AttributesController.ts
- src/modules/coreHttpApi/controllers/ChallengesController.ts
- src/modules/coreHttpApi/controllers/FilesController.ts
- src/modules/coreHttpApi/controllers/IncomingRequestsController.ts
- src/modules/coreHttpApi/controllers/MessagesController.ts
- src/modules/coreHttpApi/controllers/OutgoingRequestsController.ts
- src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
- src/modules/coreHttpApi/controllers/RelationshipsController.ts
- src/modules/coreHttpApi/controllers/TokensController.ts
- test/spec.test.ts
- [typescript-ioc](https://github.com/nmshd/typescript-ioc) is forked and it's dependencies are updated, the lib is published under `@nmshd/typescript-ioc`
- [typescript-rest](https://github.com/nmshd/typescript-rest) is also forked and it's dependencies are updated, the lib is published under `@nmshd/typescript-rest`
- typescript-rest-ioc was not be updated and the code (only one file) was moved inside the connector
> Use `@nmshd/typescript-ioc` and `@nmshd/typescript-rest` to get rid of vulnerabilities

- src/modules/coreHttpApi/openapi.yml
When loading the newest OpenAPI specification of the Connector into Postman, I've noticed that sometimes the properties of different types are listed together in the body schemas of some API routes, although only one type and thus one set of properties may be used.
> Mixed up properties in OpenAPI schemas

- src/modules/coreHttpApi/openapi.yml
Fixes nmshd/feedback#29
The openapi declaration was incorrect as ts-serval omits `@type`s that can only have one value (like in this case `"Request"`).
> `@type` is displayed as required in `onNewRelationship`

- src/modules/coreHttpApi/openapi.yml
Fixes nmshd/feedback#29
Fixed issues:
- `@type` is displayed as required in `RequestResponseContent`
- `peerIdentity` is missing in `Relationship`
> Some objects in the OpenAPI spec are incorrect

- .eslintrc
- packages/sdk/src/ConnectorClient.ts
- src/modules/webhooks/WebhooksModule.ts
- test/correlationId.test.ts
- test/errors.test.ts
> Update naming convention

- src/modules/coreHttpApi/controllers/FilesController.ts
- test/files.test.ts
-   [x] I self-reviewed the PR.
> Utf8 in filename is encoded as latin1

- src/cli/commands/identity/status.ts
- test/modules/cli/identity/identityStatus.test.ts
-   [x] I self-reviewed the PR.
@sebbi08 in #308 you named an address an id. Please make sure to inform about the differences.
> Proper Wording in Deletion CLI

- src/modules/coreHttpApi/openapi.yml
- test/files.test.ts
> Optional properties specified as required in OpenAPI

- Dockerfile
When running the connector we get the error `getaddrinfo EAI_AGAIN <domain>' for <route>` from time to time. [It looks like](https://stackoverflow.com/a/76699210) alpine could be the issue here.
> NodeJS alpine is causing DNS lookup issues

- .dev/Dockerfile.debug
- .dev/compose.prodtest.yml
- .dev/compose.yml
- README_dev.md
- helmChart/README.md
- helmChart/values.yaml
- src/infrastructure/httpServer/HttpServer.ts
Port 80 requires extended capabilities in kubernetes (`CAP_NET_BIND_SERVICE`), when switching from `alpine` to `node:slim` this capability was removed (see https://github.com/nmshd/connector/pull/354/files).
The error looks as follows:
```
[2025-02-05T18:13:08.212] [ERROR] ConnectorRuntime - Uncaught exception occured:  Error: listen EACCES: permission denied 0.0.0.0:80
at Server.setupListenHandle [as _listen2] (node:net:1915:21)
at listenInCluster (node:net:1994:12)
at Server.listen (node:net:2099:7)
at Function.listen (/usr/app/node_modules/express/lib/application.js:635:24)
at /usr/app/dist/infrastructure/httpServer/HttpServer.js:223:36
at new Promise (<anonymous>)
at HttpServer.start (/usr/app/dist/infrastructure/httpServer/HttpServer.js:221:22)
at ConnectorRuntime.startInfrastructure …
```
> Connector does not start in kubernetes

- .dev/Dockerfile.debug
- .dev/compose.prodtest.yml
- .dev/compose.yml
- README_dev.md
- helmChart/README.md
- helmChart/templates/NOTES.txt
- helmChart/templates/deployment.yaml
- helmChart/values.yaml
- src/healthcheck.ts
- src/infrastructure/httpServer/HttpServer.ts
Reverts #363 because of the unwanted breaking config change (compose users had to manually change the port to 8080).
Additionally:
- changes the port **on kubernetes only** of the pod to 8080, not configurable
- it's still possible to configure the Service port
> Connector does not start on kubernetes

- package-lock.json
- package.json
When installed using the zip (#366) the connector should make sure to not start / show a warning if an old node version is detected that we don't test for.
> Connector installs and starts under old NodeJS without a warning

- Dockerfile
- src/createConnectorConfig.ts
It was not very good idea to add file based logging by default, b/c when it's really required we should make sure that the user knows where logs are stored and how to change these settings.
As a side effect this should help setting the connector up without docker on MacOS and Windows as the path /var/log has been very linux'y
> Only log to console by default

- src/jsonSchemas/connectorConfig.json
> Starting a connector without a baseUrl configured throws a confusing error

- package-lock.json
- package.json
- src/modules/coreHttpApi/controllers/AttributesController.ts
Introduces the things @sebbi08 did in https://github.com/nmshd/typescript-rest/pull/2, and hands over the job to do the conversion to typescript-rest.
> Simplify boolean conversion

- packages/sdk/src/endpoints/FilesEndpoint.ts
- packages/sdk/src/endpoints/RelationshipTemplatesEndpoint.ts
- packages/sdk/src/endpoints/TokensEndpoint.ts
- packages/sdk/src/types/files/requests/CreateTokenQrCodeForFileRequest.ts
- packages/sdk/src/types/relationshipTemplates/requests/CreateTokenQrCodeForOwnRelationshipTemplateRequest.ts
- src/modules/coreHttpApi/controllers/FilesController.ts
- src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
- src/modules/coreHttpApi/controllers/TokensController.ts
- src/modules/coreHttpApi/openapi.yml
This is breaking as integrators have to actively change the behavior if they want to use the old reference format in QR codes.
> Switch the default QR code format to the new one and remove the old one completely

- packages/sdk/src/types/messages/requests/GetMessagesRequest.ts
- packages/sdk/src/types/relationships/requests/GetRelationshipsRequest.ts
- test/messages.test.ts
The SDK types don't match the runtime types in some deep query scenarios.
> Deep queries are incorrectly implemented in the SDK

- packages/sdk/src/endpoints/AttributesEndpoint.ts
> Peer is not required in shared Attribute getters of SDK

- packages/sdk/src/ConnectorClient.ts
To allow the SDK to be extended in custom modules, the connectorClient's constructor is set to protected (currently private).
> The SDK is not extensible
