.dev/compose.yml

Chore/Enable host-gateway dns on linux docker

---

test/attributes.test.ts

Fix missing wait for event

---

.dev/Dockerfile.debug
Dockerfile

Upgrade nodejs base image to version 22.4.1

---

package-lock.json
package.json

Upgrade the Runtime

---

packages/sdk/src/types/requests/ConnectorRequestContent.ts

DeleteAttributeRequestItem is missing in SDK

---

.dev/.env.local
.dev/compose.yml
package-lock.json
package.json
src/jsonSchemas/connectorConfig.json
src/jsonSchemas/connectorConfig.ts

Allow addressGenerationHostnameOverride in config

---

src/DocumentationLink.ts
test/errors.test.ts

Change DocumentationLink for errorCodes

---

.github/dependabot.yml

Dependabot: exclude libraries that have to be bumped as a group

---

.ci/runChecks.sh
.github/workflows/test.yml

Codecov makes problems when combined with bots like dependabot in this repo. Therefore (because it's just a tool that should help us and not annoy us) I updated the pipelines to ignore codecov upload issues.

Ignore codecov upload issues

---

.github/dependabot.yml

Group runtime Dependabot updates

---

config/default.json

Logs can not be written

---

src/modules/autoDecomposeDeletionProposedRelationships/AutoDecomposeDeletionProposedRelationshipsModule.ts

For our demos we use this module in cases where
1. the connector has been turned of during the peers identity deletion
2. the module was not activated
the modules now decomposes the relationships at startup.

Decompose relationships at connector startup in AutoDecomposeDeletionProposedRelationshipsModule

---

package-lock.json
packages/sdk/package.json
src/ConnectorRuntime.ts

Add backbone compatibility check on startup

---

.github/workflows/publish.yml
.github/workflows/test.yml

Publishing is completely broken [under Node.js 23](https://github.com/nodejs/node/issues/55410). Linked issue is closed, but fix not yet published.

Downgrade Node.js

---

src/modules/autoAcceptPendingRelationships/AutoAcceptPendingRelationshipsModule.ts
src/modules/autoDecomposeDeletionProposedRelationships/AutoDecomposeDeletionProposedRelationshipsModule.ts

Simplify code

---

LICENSE
helmChart/LICENSE
package.json
packages/sdk/LICENSE
packages/sdk/package.json
src/modules/coreHttpApi/openapi.yml

j&s-soft GmbH has now become an AG.

Change GmbH to AG

---

packages/sdk/src/ConnectorClient.ts
packages/sdk/src/endpoints/IdentityMetadataEndpoint.ts
packages/sdk/src/endpoints/index.ts
packages/sdk/src/types/identityMetadata/ConnectorIdentityMetadata.ts
packages/sdk/src/types/identityMetadata/index.ts
packages/sdk/src/types/identityMetadata/requests/UpsertIdentityMetadataRequest.ts
packages/sdk/src/types/index.ts
src/modules/coreHttpApi/controllers/IdentityMetadataController.ts
src/modules/coreHttpApi/openapi.yml
test/identityMetadata.test.ts
test/lib/validation.ts
test/spec.test.ts

Add IdentityMetadata Routes

---

packages/sdk/src/ConnectorClient.ts
test/correlationId.test.ts

-   [x] I self-reviewed the PR.
IMO this is the way cleaner alternative to #323.
@sebbi08 if you agree please close #323.

SDK CorrelationID Support

---

.github/PULL_REQUEST_TEMPLATE.md
.prettierignore
CHANGELOG.md
README_dev.md
package.json
packages/sdk/README.md

-   [x] I self-reviewed the PR.
Prettier had the wrong setup and ignored all of these files.

Prettier Setup

---

Dockerfile

Arm64 images containing amd tini version

---

Dockerfile
src/healthcheck.ts

Healthcheck is not executing

---

packages/sdk/src/types/index.ts

Monitoring types are not exported from the SDK

---

.ci/publishNpm.sh

publish pipeline does not publish all npm packages

---

.ci/buildConnectorZip.sh
.ci/publishNpm.sh
.github/workflows/publish.yml

Publish zipped connector fails because of npm package missing

---

.github/dependabot.yml
package-lock.json
packages/types/package.json

Change dependabot npm updates reviewers

---

.dev/compose.backbone.yml

Local backbone does not start

---

.dev/.env.example
.dev/.env.local
.dev/scripts/linkRuntime.sh
.github/ISSUE_TEMPLATE/config.yml
.github/workflows/publish.yml
README.md
README_dev.md
helmChart/Chart.yaml
helmChart/templates/_helpers.tpl
package.json
packages/sdk/README.md
packages/sdk/package.json
packages/sdk/src/endpoints/Endpoint.ts
packages/types/README.md
packages/types/package.json
src/ConnectorRuntime.ts
src/HealthChecker.ts
src/cli/commands/identity/status.ts
src/cli/commands/identityDeletion/cancel.ts
src/cli/commands/identityDeletion/init.ts
src/cli/commands/startConnector.ts
src/infrastructure/httpServer/middlewares/genericErrorHandler.ts
src/modules/coreHttpApi/CoreHttpApiModule.ts
src/modules/coreHttpApi/openapi.yml

Standardization of the capitalization of the terms enmeshed, Runtime, Connector, Backbone and App.

Standardized capitalization of terms

---

.github/settings.yml
package-lock.json
packages/types/package.json
packages/types/src/infrastructure/httpServer/BaseController.ts
packages/types/src/infrastructure/httpServer/common/Mimetype.ts
packages/types/src/infrastructure/httpServer/common/index.ts
packages/types/src/infrastructure/httpServer/index.ts
src/modules/coreHttpApi/controllers/AccountController.ts
src/modules/coreHttpApi/controllers/AttributesController.ts
src/modules/coreHttpApi/controllers/ChallengesController.ts
src/modules/coreHttpApi/controllers/FilesController.ts
src/modules/coreHttpApi/controllers/IdentityMetadataController.ts
src/modules/coreHttpApi/controllers/IncomingRequestsController.ts
src/modules/coreHttpApi/controllers/MessagesController.ts
src/modules/coreHttpApi/controllers/OutgoingRequestsController.ts
src/modules/coreHttpApi/controllers/RelationshipTemplatesController.ts
src/modules/coreHttpApi/controllers/RelationshipsController.ts
src/modules/coreHttpApi/controllers/TokensController.ts
src/modules/coreHttpApi/debug-controllers/IdentityDeletionProcessController.ts

I noticed that I copy more and more code from the BaseController to the custom Connector module.

Move more classes to shared types

---

package-lock.json
packages/types/package.json
packages/types/src/AbstractConnectorRuntime.ts
src/ConnectorRuntime.ts
src/createConnectorConfig.ts

This is a quality of life enhancement for writing modules:
- it's now possible to bundle a config file with the connector, when the bundled.config.json is available in the root of the connector (next to the dist directory) it overrides the hardcoded config defaults.
- the runtimeConfig is now accessible for modules
- the databaseConnection is now accessible for modules

Simplify writing modules

---

packages/types/src/AbstractConnectorRuntime.ts

Expose database information in connector runtime config

---

src/createConnectorConfig.ts

I changed it in the sources and this works.

Bundled config is not found on windows

---

.dev/test.json
packages/sdk/src/endpoints/FilesEndpoint.ts
src/modules/coreHttpApi/controllers/FilesController.ts
src/modules/coreHttpApi/openapi.yml
test/files.test.ts
test/spec.test.ts

Add deleteFile endpoint

---

package-lock.json
package.json
packages/sdk/package.json
packages/types/package.json

Add optional link text to consents

---

src/modules/webhooks/ConfigParser.ts
src/modules/webhooks/WebhooksModuleConfiguration.ts
src/modules/webhooks/authentication/ApiKeyAuthenticationProvider.ts
src/modules/webhooks/authentication/index.ts

Add ApiKey support to webhooks module

---

src/modules/webhooks/ConfigModel.ts
src/modules/webhooks/ConfigParser.ts
src/modules/webhooks/WebhooksModule.ts
src/modules/webhooks/WebhooksModuleApplicationErrors.ts
src/modules/webhooks/WebhooksModuleConfiguration.ts
src/modules/webhooks/authentication/ApiKeyTargetAuthenticator.ts
src/modules/webhooks/authentication/OAuth2TargetAuthenticator.ts
src/modules/webhooks/authentication/TargetAuthenticator.ts
src/modules/webhooks/authentication/index.ts

The Webhooks Module configuration is not named properly

---

.ncurc.json

Add ncurc.json

---

package-lock.json
package.json
packages/types/package.json
packages/types/tsconfig.json
test/tsconfig.json
tsconfig.json

Tests do not run on node 24

---

.dev/Dockerfile.debug
Dockerfile

Upgrade to node 24

---

.ci/runChecks.sh

Remove outdated audit exclude

---

src/cli/BaseCommand.ts
src/cli/commands/identity/status.ts
src/cli/commands/identityDeletion/cancel.ts
src/cli/commands/identityDeletion/init.ts

Cli commands do not exit with 1 on error

---

.github/workflows/publish.yml
.github/workflows/test.yml

Downgrade helm

---

.github/workflows/publish.yml
.github/workflows/test.yml

Upgrade helm again

---

src/ConnectorRuntime.ts
src/createConnectorConfig.ts

The non existing module AttributeListenerModule is enabled

---

src/modules/coreHttpApi/openapi.yml

Mimetype regex is crashing the swagger parser

---

.dev/scripts/establishRelationshipAndSpamMessages.ts
packages/sdk/README.md
packages/sdk/src/ConnectorClient.ts
packages/sdk/src/ConnectorClientConfig.ts

Remove apiKey field from ConnectorClientConfig

---

src/index.ts

Having no subcommand is not giving a help

---

packages/sdk/src/endpoints/index.ts
packages/sdk/src/index.ts

Undoes changes from https://github.com/nmshd/connector/pull/624 because that PR literally changed nothing and do it properly.

The endpoint class is not exported from the SDK

---

package-lock.json
packages/types/package.json

The types are resolving a non working version of the runtime

---

src/modules/sse/SseModule.ts

This should help us to find out why SSE stops working from time to time.

The SSEModule error logs are not helpful for finding connection issues

---

README_dev.md

Remove wrong SDK publish paragraph from the developer README
